"use client";
import Link from "next/link";
import {useState} from "react";
import {dateLabel, useResource} from "@/lib/api";
import type {Alert, Notification} from "@/lib/types";
import {Empty, ErrorBox, Icon, Loading, PageHeader, SeverityBadge, Stat} from "@/components/ui";

export default function AlertsPage() {
  const alerts = useResource<Alert[]>("alerts");
  const notifications = useResource<Notification[]>("notifications");
  const [severity, setSeverity] = useState("all");
  const [kind, setKind] = useState("all");
  const data = alerts.data || [];
  const filtered = data.filter(alert => (severity === "all" || alert.severity === severity) && (kind === "all" || alert.kind === kind));
  const priority = {critico: 0, importante: 1, menor: 2};
  const ordered = [...filtered].sort((a, b) => priority[a.severity] - priority[b.severity] || (a.deadline || "9999").localeCompare(b.deadline || "9999"));
  return <>
    <PageHeader eyebrow="ANTICIPACIÓN Y RESPUESTA" title="Lo importante, a tiempo." description="Alertas calculadas contra el límite de ingreso; los reportes de falla generan una alerta sin esperar el siguiente umbral." action={<button className="button secondary" onClick={() => {alerts.refresh(); notifications.refresh();}} disabled={alerts.loading}><Icon name="refresh" size={17}/>Actualizar</button>}/>
    {alerts.error && <ErrorBox message={alerts.error} retry={alerts.refresh}/>}
    <div className="stats-grid three"><Stat label="CRÍTICAS" value={alerts.data ? data.filter(a => a.severity === "critico").length : "—"} note="Detener y coordinar atención segura" accent="red"/><Stat label="IMPORTANTES" value={alerts.data ? data.filter(a => a.severity === "importante").length : "—"} note="Evaluar y planear con anticipación" accent="amber"/><Stat label="MENORES" value={alerts.data ? data.filter(a => a.severity === "menor").length : "—"} note="Diferir solo si fue evaluado"/></div>
    <section className="panel"><div className="panel-header"><div><p className="eyebrow">BANDEJA OPERATIVA</p><h2>Alertas abiertas</h2></div><span className="muted small">{ordered.length} resultados</span></div><div className="table-toolbar"><label><span className="sr-only">Severidad de alerta</span><select value={severity} onChange={e => setSeverity(e.target.value)}><option value="all">Todas las severidades</option><option value="critico">Crítico</option><option value="importante">Importante</option><option value="menor">Menor</option></select></label><label><span className="sr-only">Origen de alerta</span><select value={kind} onChange={e => setKind(e.target.value)}><option value="all">Todos los orígenes</option><option value="maintenance">Mantenimiento</option><option value="fault">Fallas reportadas</option><option value="data">Validación de datos</option></select></label></div>
      {alerts.loading && !alerts.data ? <Loading/> : !ordered.length ? <Empty title="Sin alertas para este filtro">Revisa también las unidades con datos insuficientes; la ausencia de alertas no acredita su condición mecánica.</Empty> : <div className="alerts-list">{ordered.map(alert => <article key={alert.key || alert.id} className={`alert-card ${alert.severity}`}><div className="alert-symbol"><Icon name={alert.kind === "fault" ? "warning" : "bell"} size={22}/></div><div className="alert-content"><div className="inline gap wrap"><SeverityBadge value={alert.severity}/><span className="alert-kind">{({maintenance: "Mantenimiento", fault: "Falla reportada", data: "Validación de datos"})[alert.kind] || alert.kind}</span><Link className="plate-link" href={`/vehiculos/${alert.vehicle_id}`}>{alert.plate || `Unidad ${alert.vehicle_id}`}</Link></div><h3>{alert.message}</h3><div className="inline gap wrap muted small"><span>Límite: {dateLabel(alert.deadline)}</span>{alert.days_remaining != null && <span>{alert.days_remaining < 0 ? `${Math.abs(alert.days_remaining)} días vencido` : alert.days_remaining === 0 ? "Hoy" : `${alert.days_remaining} días restantes`}</span>}{alert.threshold_days != null && <span>Umbral: {alert.threshold_days} días</span>}</div>{alert.severity === "critico" && <p className="critical-text">Atención inmediata. No seguir operando ni conducir al taller; coordinar asistencia segura.</p>}</div><Link href={`/vehiculos/${alert.vehicle_id}`} className="icon-link" aria-label={`Atender alerta de ${alert.plate || `unidad ${alert.vehicle_id}`}`}><Icon name="arrow"/></Link></article>)}</div>}
    </section>
    <section className="panel"><div className="panel-header"><div><p className="eyebrow">CANALES DE NOTIFICACIÓN</p><h2>Bandeja de salida simulada</h2></div><span className="badge neutral">SIN ENVÍOS REALES</span></div><p className="section-note">Correo y WhatsApp son adaptadores de demostración. Estos registros no acreditan entrega ni contacto con el operador.</p>{notifications.error && <div className="panel-body"><ErrorBox message={notifications.error} retry={notifications.refresh}/></div>}{notifications.loading && !notifications.data ? <Loading label="Consultando notificaciones simuladas…"/> : !notifications.data?.length ? <Empty title="Aún no hay notificaciones simuladas"/> : <div className="table-scroll"><table><thead><tr><th>Canal</th><th>Estado</th><th>Referencia</th><th>Registro</th></tr></thead><tbody>{notifications.data.slice(0, 100).map(notification => <tr key={notification.id}><td>{notification.channel === "email" ? "Correo" : notification.channel === "whatsapp" ? "WhatsApp" : notification.channel || "Simulado"}</td><td><span className="badge neutral">Simulado · no enviado</span></td><td>{notification.message || String(notification.payload?.message || `Notificación #${notification.id}`)}</td><td>{dateLabel(notification.created_at)}</td></tr>)}</tbody></table>{notifications.data.length > 100 && <p className="section-note">Se muestran los primeros 100 registros de {notifications.data.length}.</p>}</div>}</section>
  </>;
}
