"use client";
import Link from "next/link";
import {useParams} from "next/navigation";
import {useState} from "react";
import {api, dateLabel, localDate, numberLabel, useResource} from "@/lib/api";
import type {Fault, Plan, ServicePlan, VehicleDetail} from "@/lib/types";
import {Empty, ErrorBox, Icon, Loading, MutationForm, PageHeader, SeverityBadge, Stat, StatusBadge, TrafficBadge, VisitCard} from "@/components/ui";
import {DowntimePanel, ReadingForm, ReadingHistory, ServiceForm, ServiceHistoryTable, UsageConditions} from "@/components/vehicle-records";

function ServiceRow({service}: {service: ServicePlan}) {
  return <article className={`service-row ${service.status}`}><div className="service-main"><div><div className="inline gap wrap"><h3>{service.name}</h3><StatusBadge status={service.status}/></div><p className="muted small">{service.action} · Confianza {service.confidence}{service.requires_validation ? " · Requiere validación" : ""}</p></div><SeverityBadge value={service.severity}/></div>
    <div className="service-dates"><div><span>Vencimiento probable</span><strong>{dateLabel(service.due_date)}</strong><small>{service.due_odometer == null ? "Sin intervalo por km" : `${numberLabel(service.due_odometer)} km de odómetro`}</small></div><div className="deadline"><span>Límite conservador provisional</span><strong>{dateLabel(service.latest_entry_date)}</strong><small>{service.km_remaining == null ? "Sin kilometraje calculable" : `${numberLabel(service.km_remaining)} km restantes`}</small></div><div><span>Ventana de agrupación</span><strong>{service.window_start && service.window_end ? `${dateLabel(service.window_start)} — ${dateLabel(service.window_end)}` : "Sin ventana validada"}</strong><small>{service.duration_hours == null ? "Tiempo en taller por validar" : `${numberLabel(service.duration_hours, 1)} h estimadas`}</small></div></div>
    <details className="service-details"><summary>Ver criterio, incertidumbre y fuentes</summary><p>{service.explanation}</p><dl className="uncertainty"><div><dt>Uso alto / fecha temprana</dt><dd>{dateLabel(service.prediction.pessimistic)}</dd></div><div><dt>Uso probable</dt><dd>{dateLabel(service.prediction.probable)}</dd></div><div><dt>Uso bajo / fecha tardía</dt><dd>{dateLabel(service.prediction.optimistic)}</dd></div></dl><p className="small muted">El rango describe incertidumbre de uso, no un permiso para retrasar el servicio.</p><div className="source-links">{service.source_urls.filter(url => /^https:\/\//.test(url)).map((url, index) => <a key={`${url}-${index}`} href={url} target="_blank" rel="noopener noreferrer">Fuente {index + 1} ↗</a>)}</div></details>
  </article>;
}

function FaultItem({fault, onDone}: {fault: Fault; onDone: () => void}) {
  const [resolving, setResolving] = useState(false);
  return <article className={`fault-card ${fault.severity}`}><div className="inline gap wrap"><SeverityBadge value={fault.severity}/><StatusBadge status={fault.status}/>{fault.dtc && <code>{fault.dtc}</code>}<span className="muted small">{dateLabel(fault.reported_on)}</span></div><h3>{fault.description}</h3>
    <p className="muted small">{fault.was_predicted == null ? "Sin clasificación de previsión" : fault.was_predicted ? "Falla prevista según evaluación registrada" : "Falla no prevista según evaluación registrada"}</p>
    {fault.status === "open" && <><p className="small">{fault.severity === "critico" ? "Atención inmediata. Detener la operación y coordinar asistencia; no conducir la unidad al taller." : fault.safe_to_defer && fault.deadline ? `Diferimiento evaluado hasta ${dateLabel(fault.deadline)}. Vigilar cualquier cambio.` : "Requiere evaluación. No hay autorización de uso o diferimiento por ausencia de una fecha."}</p>{fault.assessment_message && <p className="muted small">{fault.assessment_message}</p>}</>}
    {fault.status === "resolved" ? <p className="muted small">Resolución: {fault.resolution_notes || "Sin notas"}</p> : <><button type="button" className="text-button" onClick={() => setResolving(value => !value)} aria-expanded={resolving}>{resolving ? "Cancelar resolución" : "Registrar resolución"}</button>{resolving && <MutationForm title="Confirmar resolución de la falla" description="Hazlo únicamente cuando el problema haya sido revisado y solucionado. Se conserva el historial." submitLabel="Confirmar falla resuelta" onDone={() => {setResolving(false); onDone();}} onSave={async data => {await api(`faults/${fault.id}/resolve`, {method: "PATCH", body: {resolution_notes: data.get("resolution_notes")}}); return "Falla resuelta; plan actualizado.";}}><label>Trabajo realizado y verificación<textarea name="resolution_notes" required minLength={8} maxLength={2000} rows={3}/></label><label className="check-label"><input type="checkbox" required/>Confirmo que se evaluó y resolvió esta falla</label></MutationForm>}</>}
  </article>;
}

function RegisterFault({id, services, onDone}: {id: string; services: ServicePlan[]; onDone: () => void}) {
  const [severity, setSeverity] = useState("importante");
  const [safe, setSafe] = useState(false);
  return <MutationForm title="Reportar falla" description="Un código DTC orienta el diagnóstico, pero no identifica por sí solo una pieza defectuosa. La alerta se genera al registrar el reporte." submitLabel="Registrar falla y alertar" onDone={onDone} onSave={async data => {
    await api(`vehicles/${id}/faults`, {method: "POST", body: {description: data.get("description"), dtc: String(data.get("dtc") || "").trim().toUpperCase() || null, severity, safe_to_defer: severity !== "critico" && safe, deadline: severity !== "critico" && safe ? data.get("deadline") : null, assessment_notes: severity !== "critico" && safe ? String(data.get("assessment_notes") || "") : "", service_id: data.get("service_id") || null, was_predicted: data.get("was_predicted") === "unknown" ? null : data.get("was_predicted") === "true"}});
    return "Falla registrada. Revisa la alerta y el plan actualizados.";
  }}><label>Descripción del síntoma<textarea name="description" required minLength={8} maxLength={3000} rows={3} placeholder="Qué ocurrió, cuándo y en qué condiciones…"/></label><div className="form-grid"><label>Código DTC (opcional)<input name="dtc" maxLength={12} pattern="[PCBUpcbu][0-3][0-9A-Fa-f]{3}(:[0-9A-Fa-f]{2})?" placeholder="Ej. P0126"/></label><label>Severidad<select value={severity} onChange={e => {setSeverity(e.target.value); setSafe(false);}}><option value="critico">Crítico · atención inmediata</option><option value="importante">Importante · evaluar</option><option value="menor">Menor · evaluar agrupación</option></select></label></div>
    <div className="form-grid"><label>Componente relacionado (opcional)<select name="service_id" defaultValue=""><option value="">Sin identificar</option>{services.map(service => <option key={service.service_id} value={service.service_id}>{service.name}</option>)}</select></label><label>¿Se había previsto esta falla?<select name="was_predicted" defaultValue="unknown"><option value="unknown">No evaluado</option><option value="false">No, fue inesperada</option><option value="true">Sí, había evidencia previa</option></select><span className="field-help">Clasificación humana para métricas; no es un diagnóstico automático.</span></label></div>
    {severity === "critico" ? <p className="message error">Detén la operación. Coordina asistencia y traslado seguro; no conduzcas al taller ni esperes una visita agrupada.</p> : <><label className="check-label"><input type="checkbox" checked={safe} onChange={e => setSafe(e.target.checked)}/>Un técnico evaluó la falla y autorizó un diferimiento con fecha límite</label>{safe && <><label>Fecha límite evaluada<input name="deadline" type="date" required min={localDate()}/><span className="field-help">No es una tolerancia calculada por el sistema.</span></label><label>Evaluación y responsable<textarea name="assessment_notes" required minLength={12} maxLength={2000} rows={3} placeholder="Quién evaluó la falla y por qué se autoriza diferirla…"/></label></>}</>}
  </MutationForm>;
}

export default function VehiclePage() {
  const params = useParams<{id: string}>();
  const id = params.id;
  const detail = useResource<VehicleDetail>(`vehicles/${id}`);
  const plan = useResource<Plan>(`vehicles/${id}/plan`);
  const [activeForm, setActiveForm] = useState("reading");
  const [serviceFilter, setServiceFilter] = useState("all");
  const refresh = () => {detail.refresh(); plan.refresh();};
  if (!detail.data || !plan.data) return <><PageHeader eyebrow="DETALLE DE UNIDAD" title="Plan de mantenimiento" description="Cargando historial, uso y proyecciones."/>{detail.error && <ErrorBox message={detail.error} retry={detail.refresh}/>} {plan.error && <ErrorBox message={plan.error} retry={plan.refresh}/>} {(detail.loading || plan.loading) && <Loading/>}</>;
  const {vehicle, readings, history, faults, downtime = []} = detail.data;
  const projection = plan.data;
  const names = Object.fromEntries(projection.services.map(s => [s.service_id, s.name]));
  const services = projection.services.filter(service => serviceFilter === "all" || (serviceFilter === "scheduled" ? service.due_date : service.requires_validation || service.status === "pending_validation"));
  const openFaults = faults.filter(fault => fault.status === "open");
  return <>
    <Link href="/" className="back-link">← Volver a flotilla</Link><PageHeader eyebrow={`MAZDA3 · ${vehicle.model_year} · ${vehicle.body_style.toUpperCase()}`} title={vehicle.plate} description={`${vehicle.version} · ${vehicle.engine} · ${vehicle.transmission} · ${vehicle.drive}`} action={<button className="button secondary" onClick={refresh} disabled={detail.loading || plan.loading}><Icon name="refresh" size={17}/>Actualizar</button>}/>
    <div className="vehicle-meta"><TrafficBadge value={projection.traffic_light}/><span>VIN <code>{vehicle.vin}</code></span><span>Uso {vehicle.usage_regime === "severe" ? "severo" : "normal"}</span><span>Factor de intervalo: {numberLabel(vehicle.severity_multiplier ?? 1, 2)}</span>{vehicle.is_synthetic && <span className="badge neutral">Unidad sintética</span>}<span className="badge neutral">Catálogo {projection.catalog_version}</span></div>
    {detail.error && <ErrorBox message={detail.error} retry={detail.refresh}/>}{plan.error && <ErrorBox message={plan.error} retry={plan.refresh}/>}
    {openFaults.some(f => f.severity === "critico") && <div className="message error critical-callout" role="alert"><Icon name="warning"/><div><strong>Falla crítica abierta: detener la operación</strong><p>Coordina atención inmediata y traslado seguro. No conduzcas la unidad al taller; no se debe esperar a la fecha agrupada.</p></div></div>}
    <div className="stats-grid"><Stat label="ODÓMETRO ACTUAL" value={`${numberLabel(vehicle.current_km)} km`} note={`En servicio desde ${dateLabel(vehicle.in_service_date)}`}/><Stat label="USO DIARIO ESTIMADO" value={`${numberLabel(projection.usage.km_per_day, 1)} km`} note={`${numberLabel(projection.usage.low_km_per_day, 1)}–${numberLabel(projection.usage.high_km_per_day, 1)} km/día de incertidumbre`}/><Stat label="CONFIANZA DEL USO" value={projection.usage.confidence} note={`${projection.usage.valid_intervals} intervalos válidos`}/><Stat label="FALLAS ABIERTAS" value={openFaults.length} note="Reportes reales / DTC registrados" accent={openFaults.some(f => f.severity === "critico") ? "red" : undefined}/></div>
    {projection.warnings.length > 0 && <details className="panel warning-panel"><summary><Icon name="warning" size={18}/>{projection.warnings.length} advertencias de datos y validación</summary><ul>{projection.warnings.map((warning, index) => <li key={index}>{warning}</li>)}</ul></details>}
    <section className="panel"><div className="panel-header"><div><p className="eyebrow">MENOS INGRESOS, MEJOR PLANEACIÓN</p><h2>Visitas propuestas</h2></div><span className="muted small">Cálculo: {dateLabel(projection.generated_on)}</span></div><div className="panel-body">{projection.visits.length ? projection.visits.map(visit => <VisitCard key={visit.id} visit={visit} names={names}/>) : <Empty title="Todavía no hay una visita calculable">Completa el historial y valida las reglas pendientes. La ausencia de fecha no significa que la unidad esté libre de mantenimiento.</Empty>}</div></section>
    <section className="panel"><div className="panel-header"><div><p className="eyebrow">CRITERIO QUE VENZA PRIMERO</p><h2>Próximos servicios</h2></div><label><span className="sr-only">Filtrar servicios</span><select value={serviceFilter} onChange={e => setServiceFilter(e.target.value)}><option value="all">Todos los servicios</option><option value="scheduled">Con proyección de fecha</option><option value="pending">Requieren validación</option></select></label></div><p className="section-note">Las fechas son referencias provisionales; no se extienden límites con tolerancias no validadas.</p>{services.length ? services.map(service => <ServiceRow key={service.service_id} service={service}/>) : <Empty title="Sin servicios para este filtro"/>}</section>
    <div className="detail-columns"><section className="panel"><div className="panel-header"><div><p className="eyebrow">MANTÉN EL HISTORIAL AL DÍA</p><h2>Registrar movimiento</h2></div></div><div className="segmented" aria-label="Tipo de registro">{[["reading", "Odómetro"], ["service", "Servicio"], ["fault", "Falla"]].map(([value, label]) => <button key={value} className={activeForm === value ? "selected" : ""} onClick={() => setActiveForm(value)} aria-pressed={activeForm === value}>{label}</button>)}</div><div className="panel-body">
      {activeForm === "reading" && <ReadingForm id={id} vehicle={vehicle} onDone={refresh}/>}
      {activeForm === "service" && <ServiceForm id={id} vehicle={vehicle} services={projection.services} faults={faults} onDone={refresh}/>}
      {activeForm === "fault" && <RegisterFault id={id} services={projection.services} onDone={refresh}/>}
    </div></section><section className="panel"><div className="panel-header"><div><p className="eyebrow">EVALUACIÓN HUMANA</p><h2>Fallas reportadas</h2></div></div><div className="panel-body">{faults.length ? [...faults].sort((a, b) => Number(a.status === "resolved") - Number(b.status === "resolved")).map(fault => <FaultItem key={fault.id} fault={fault} onDone={refresh}/>) : <Empty title="Sin fallas reportadas">Esto no constituye una evaluación mecánica de la unidad.</Empty>}</div></section></div>
    <div className="detail-columns"><section className="panel"><div className="panel-header"><h2>Historial de odómetro</h2><span className="muted small">{readings.length} lecturas</span></div><div className="panel-body"><p className="muted small">{projection.usage.explanation}</p>{projection.usage.rejected_readings > 0 && <p className="small">Lecturas descartadas para estimación: {projection.usage.rejected_readings}</p>}</div><ReadingHistory readings={readings}/></section>
      <section className="panel"><div className="panel-header"><h2>Servicios realizados</h2><span className="muted small">{history.length} registros</span></div><ServiceHistoryTable history={history} names={names}/></section></div>
    <UsageConditions id={id} vehicle={vehicle} onDone={refresh}/>
    <DowntimePanel id={id} vehicle={vehicle} entries={downtime} onDone={refresh}/>
  </>;
}
