"""Adaptador de persistencia del motor puro: auditoría e idempotencia."""
from datetime import date, datetime
import hashlib
import json
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.orm import Session

from .engine import build_plan
from .models import Alert, FaultReport, Notification, OdometerReading, PlanEvaluation, ServiceHistory, Vehicle, VisitPlan
from .notifications import SimulatedChannel

ENGINE_SHA256 = hashlib.sha256(Path(__file__).with_name("engine.py").read_bytes()).hexdigest()


def current_date() -> date:
    """Replaceable clock for persistence tests; engine still receives explicit date."""
    return date.today()


def serialize(row) -> dict:
    return {column.name: (value.isoformat() if isinstance(value, (date, datetime)) else value)
            for column in row.__table__.columns if (value := getattr(row, column.name)) is not ...}


def stable_hash(value: dict) -> str:
    return hashlib.sha256(json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def vehicle_inputs(session: Session, vehicle: Vehicle) -> dict:
    return {
        "vehicle": serialize(vehicle),
        "readings": [serialize(row) for row in session.scalars(select(OdometerReading).where(OdometerReading.vehicle_id == vehicle.id).order_by(OdometerReading.date, OdometerReading.id))],
        "history": [serialize(row) for row in session.scalars(select(ServiceHistory).where(ServiceHistory.vehicle_id == vehicle.id).order_by(ServiceHistory.performed_on, ServiceHistory.id))],
        "faults": [serialize(row) for row in session.scalars(select(FaultReport).where(FaultReport.vehicle_id == vehicle.id).order_by(FaultReport.id))],
    }


def evaluate(session: Session, vehicle: Vehicle, catalog: dict, policy: dict) -> dict:
    inputs = vehicle_inputs(session, vehicle)
    today = current_date()
    fingerprint = stable_hash({"today": today.isoformat(), "inputs": inputs, "catalog": catalog, "policy": policy, "engine_sha256": ENGINE_SHA256})
    cached = session.scalar(select(PlanEvaluation).where(PlanEvaluation.fingerprint == fingerprint))
    if cached:
        evaluation, result = cached, cached.result
    else:
        result = build_plan(**inputs, catalog=catalog, config=policy, today=today)
        evaluation = PlanEvaluation(vehicle_id=vehicle.id, fingerprint=fingerprint,
                                    catalog_version=catalog["version_catalogo"], policy_version=policy["policy_version"],
                                    inputs_snapshot={**inputs, "runtime": {"engine_sha256": ENGINE_SHA256}},
                                    catalog_snapshot=catalog, policy_snapshot=policy, result=result)
        session.add(evaluation)
        session.flush()
    # Even a cached evaluation must reconcile materialized projections: restoring
    # a previous policy must archive alerts/visits generated by the newer policy.
    current_alerts = {row.key: row for row in session.scalars(select(Alert).where(Alert.vehicle_id == vehicle.id))}
    active_keys = set()
    for payload in result["alerts"]:
        key = f"{vehicle.id}:{payload['key']}"
        active_keys.add(key)
        alert = current_alerts.get(key)
        if alert is None:
            alert = Alert(key=key, vehicle_id=vehicle.id, evaluation_id=evaluation.id, generation=1, payload=payload)
            session.add(alert)
        elif alert.status != "open":
            alert.generation += 1
        alert.status = "open"
        alert.evaluation_id = evaluation.id
        alert.service_id = payload.get("service_id")
        alert.fault_id = payload.get("fault_id")
        alert.payload = payload
        session.flush()
        anchors = [row for row in inputs["history"] if row["service_id"] == alert.service_id]
        cycle = max(((row["performed_on"], row["id"]) for row in anchors), default=(vehicle.in_service_date.isoformat(), 0))
        for channel in ("email", "whatsapp"):
            dedup = stable_hash({"key": key, "generation": alert.generation, "channel": channel,
                                 "cycle": cycle, "threshold": payload.get("threshold_days"),
                                 "severity": payload["severity"]})
            if session.scalar(select(Notification.id).where(Notification.dedup_key == dedup)) is None:
                session.add(Notification(dedup_key=dedup, alert_id=alert.id, channel=channel,
                                         payload=SimulatedChannel(channel).deliver(payload)))
    for key, alert in current_alerts.items():
        if key not in active_keys:
            alert.status = "resolved" if alert.fault_id else "archived"
    current_visits = {row.id: row for row in session.scalars(select(VisitPlan).where(VisitPlan.vehicle_id == vehicle.id))}
    active_visits = set()
    for payload in result["visits"]:
        key = f"{vehicle.id}:{payload['id']}"
        active_visits.add(key)
        visit = current_visits.get(key)
        if visit is None:
            visit = VisitPlan(id=key, vehicle_id=vehicle.id, evaluation_id=evaluation.id,
                              planned_date=date.fromisoformat(payload["planned_date"]), payload=payload)
            session.add(visit)
        visit.status = "proposed"
        visit.evaluation_id = evaluation.id
        visit.planned_date = date.fromisoformat(payload["planned_date"])
        visit.payload = payload
    for key, visit in current_visits.items():
        if key not in active_visits:
            visit.status = "archived"
    session.flush()
    return result
