import {test, expect} from "@playwright/test";
import {localDate} from "../lib/dates";

const origin = "http://127.0.0.1:3001";
const isoDay = (offset = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return localDate(d);
};

test("flotilla sintética, detalle, calendario, alertas y vista móvil", async ({page}, testInfo) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/");
  await expect(page.getByRole("heading", {name: "Más tiempo en ruta."})).toBeVisible();
  await expect(page.getByRole("link", {name: "DEMO-020", exact: true})).toBeVisible();
  await page.screenshot({path: testInfo.outputPath("flotilla-desktop.png"), fullPage: true});
  await page.getByRole("link", {name: "DEMO-004", exact: true}).click();
  await expect(page.getByRole("heading", {name: "DEMO-004", exact: true})).toBeVisible();
  await expect(page.getByText("Sin historial de servicios", {exact: true})).toBeVisible();
  await expect(page.getByText("baja", {exact: true}).first()).toBeVisible();
  await page.goto("/calendario");
  await expect(page.getByRole("heading", {name: "Una agenda, menos paradas."})).toBeVisible();
  await expect(page.getByRole("link", {name: "DEMO-001", exact: true}).first()).toBeVisible();
  await page.screenshot({path: testInfo.outputPath("calendario-desktop.png"), fullPage: true});
  await page.goto("/alertas");
  await expect(page.getByRole("heading", {name: "Bandeja de salida simulada"})).toBeVisible();
  await page.getByLabel("Severidad de alerta").selectOption("critico");
  await page.getByLabel("Origen de alerta").selectOption("fault");
  await expect(page.locator(".alert-card.critico").first()).toBeVisible();
  await expect(page.getByText("SIN ENVÍOS REALES", {exact: true})).toBeVisible();
  await page.setViewportSize({width: 390, height: 844});
  await page.goto("/");
  await expect(page.getByRole("heading", {name: "Más tiempo en ruta."})).toBeVisible();
  await expect(page.getByRole("link", {name: "DEMO-001", exact: true})).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy();
  await page.screenshot({path: testInfo.outputPath("flotilla-movil.png"), fullPage: true});
  expect(errors).toEqual([]);
});

test("alta sintética y registro real de lectura, servicio, falla y resolución", async ({page, request}) => {
  const variantsResponse = await request.get("/api/backend/variants");
  expect(variantsResponse.ok()).toBeTruthy();
  const variants = (await variantsResponse.json()).variantes;
  const variant = variants.find((v: {motor: string}) => v.motor === "G25");
  const suffix = String(Date.now()).slice(-14).padStart(14, "0");
  const plate = `E2E-${suffix.slice(-10)}`;
  await page.goto("/");
  await page.getByRole("button", {name: "Agregar unidad", exact: true}).click();
  await page.getByLabel("Número de serie (VIN)", {exact: true}).fill(`TST${suffix}`);
  await page.getByLabel("Placas", {exact: true}).fill(plate);
  await page.getByLabel("Plantilla de vehículo").selectOption("mazda3");
  await page.getByLabel("Modelo Mazda3 del catálogo").selectOption(variant.id);
  await page.getByLabel("Transmisión", {exact: true}).fill(variant.transmisiones[0]);
  await page.getByLabel("Odómetro actual (km)").fill("10000");
  await page.getByLabel("Fecha de puesta en servicio").fill(isoDay(-180));
  await page.getByLabel("Esta unidad es un dato sintético de demostración").check();
  await page.getByRole("button", {name: "Agregar a flotilla"}).click();
  await expect(page.getByText("Unidad registrada. Agrega sus lecturas y servicios para mejorar la proyección.")).toBeVisible();
  await page.getByLabel("Buscar por placa").fill(plate);
  await page.getByRole("link", {name: plate, exact: true}).click();
  await expect(page.getByRole("heading", {name: plate, exact: true})).toBeVisible();
  await page.getByLabel("Fecha y hora de lectura (CDMX)").fill(`${isoDay(-1)}T12:00`);
  await page.getByLabel("Odómetro (km)", {exact: true}).fill("9900");
  await page.getByRole("button", {name: "Guardar registro", exact: true}).click();
  await expect(page.getByText("Lectura guardada. Proyección recalculada.")).toBeVisible();
  await page.getByRole("button", {name: "Guardar registro", exact: true}).click();
  await expect(page.getByRole("alert").filter({hasText: "No pudimos completar"})).toBeVisible();
  await page.getByRole("button", {name: "Servicio", exact: true}).click();
  await page.getByLabel("Servicio del catálogo").selectOption("aceite_normal");
  await page.getByLabel("Odómetro al realizarlo (km)").fill("10000");
  await page.getByLabel("Notas del trabajo").fill("Servicio sintético de prueba E2E, no mantenimiento de una unidad real.");
  await page.getByRole("button", {name: "Guardar registro", exact: true}).click();
  await expect(page.getByText("Servicio registrado. Plan y métricas actualizados.")).toBeVisible();
  await page.getByRole("button", {name: "Falla", exact: true}).click();
  await page.getByLabel("Descripción del síntoma").fill("Prueba sintética: pérdida de frenado; la unidad no frena.");
  // Explicit critical input checks the complete user-facing urgent flow.
  await page.getByRole("combobox", {name: "Severidad", exact: true}).selectOption("critico");
  await expect(page.getByText("Detén la operación. Coordina asistencia y traslado seguro; no conduzcas al taller ni esperes una visita agrupada.")).toBeVisible();
  await page.getByRole("button", {name: "Registrar falla y alertar"}).click();
  await expect(page.getByText("Falla crítica abierta: detener la operación")).toBeVisible();
  await page.reload();
  await expect(page.getByText("Falla crítica abierta: detener la operación")).toBeVisible();
  await page.getByRole("button", {name: "Registrar resolución"}).click();
  await page.getByLabel("Trabajo realizado y verificación").fill("Resolución sintética E2E: técnico verificó y reparó el sistema de frenos.");
  await page.getByLabel("Confirmo que se evaluó y resolvió esta falla").check();
  await page.getByRole("button", {name: "Confirmar falla resuelta"}).click();
  await expect(page.getByText("Resuelta", {exact: true})).toBeVisible();
  await expect(page.getByText("Falla crítica abierta: detener la operación")).toHaveCount(0);
  await page.getByRole("button", {name: "Falla", exact: true}).click();
  await page.getByLabel("Descripción del síntoma").fill("Ruido leve de moldura interior, prueba sintética evaluada sin riesgo de seguridad.");
  await page.getByRole("combobox", {name: "Severidad", exact: true}).selectOption("menor");
  await page.getByLabel("Un técnico evaluó la falla y autorizó un diferimiento con fecha límite").check();
  await page.getByLabel("Fecha límite evaluada").fill(isoDay(5));
  await page.getByLabel("Evaluación y responsable").fill("Técnico de prueba: moldura suelta sin afectar controles; reparar en cinco días.");
  await page.getByRole("button", {name: "Registrar falla y alertar"}).click();
  await expect(page.getByText(/Diferimiento evaluado hasta/)).toBeVisible();
});

test("API y proxy cierran accesos no autorizados", async ({request}) => {
  const health = await request.get("http://127.0.0.1:8000/health");
  expect(health.ok()).toBeTruthy();
  const noKey = await request.get("http://127.0.0.1:8000/api/vehicles");
  expect([401, 403]).toContain(noKey.status());
  const foreign = await request.post("/api/backend/recalculate", {headers: {Origin: "https://example.invalid"}});
  expect(foreign.status()).toBe(403);
  const crossSiteRead = await request.get("/api/backend/vehicles", {headers: {"Sec-Fetch-Site": "cross-site"}});
  expect(crossSiteRead.status()).toBe(403);
  const unknown = await request.get("/api/backend/private-files");
  expect(unknown.status()).toBe(404);
  const invalid = await request.post("/api/backend/vehicles", {headers: {Origin: origin}, data: {vin: "INVALID"}});
  expect(invalid.status()).toBe(422);
});
