import {test, expect} from "@playwright/test";

test.use({baseURL: process.env.YOKOHAMA_PROPOSAL_TEST_URL || "http://127.0.0.1:3004", channel: "chromium"});
const isoDay = (delta: number) => {const date = new Date(); date.setUTCDate(date.getUTCDate() + delta); return date.toISOString().slice(0, 10);};

test("la propuesta conserva cambios de agenda y captura atrasada al recargar", async ({page}, info) => {
  await page.goto("/");
  await expect(page.getByText("Prueba la propuesta.")).toBeVisible();
  await expect(page.locator(".plate-link").first()).toBeVisible();
  expect(await page.locator(".plate-link").allTextContents()).not.toContain("DEMO-001");
  await page.getByRole("link", {name: "Calendario", exact: true}).click();
  const entry = page.locator(".agenda-entry").filter({has: page.getByRole("button", {name: "Cambiar fecha", exact: true})}).first();
  const plate = await entry.locator(".plate-link").innerText();
  await entry.getByRole("button", {name: "Cambiar fecha", exact: true}).click();
  const scheduled = isoDay(35);
  await page.getByLabel("Nueva fecha de la visita").fill(scheduled);
  await page.getByLabel("Motivo del cambio (opcional)").fill("La empresa confirmó otro día con el taller.");
  await page.getByRole("button", {name: "Guardar nueva fecha"}).click();
  await expect(page.getByText("Guardado", {exact: true})).toBeVisible();
  await expect(page.getByLabel("Mes de visitas")).toHaveValue(scheduled.slice(0, 7));
  await page.reload();
  await page.getByLabel("Mes de visitas").fill(scheduled.slice(0, 7));
  const scheduledEntry = page.locator(".agenda-entry").filter({hasText: plate}).filter({hasText: "Fecha registrada"}).first();
  await expect(scheduledEntry).toBeVisible();
  await scheduledEntry.getByRole("button", {name: "Registrar realizado", exact: true}).click();
  const performed = isoDay(-3);
  await page.getByLabel("Fecha real del servicio").fill(performed);
  await page.getByLabel("Notas o referencia del comprobante (opcional)").fill("Comprobante recibido tres días después. Sin lectura de kilometraje.");
  await page.getByRole("button", {name: "Guardar servicio realizado"}).click();
  await expect(page.getByText("Guardado", {exact: true})).toBeVisible();
  await expect(page.getByLabel("Mes de visitas")).toHaveValue(performed.slice(0, 7));
  await page.reload();
  await page.getByLabel("Mes de visitas").fill(performed.slice(0, 7));
  await page.getByLabel("Filtrar agenda").selectOption("completed");
  await page.getByRole("searchbox", {name: "Buscar por placa", exact: true}).fill(plate);
  await expect(page.locator(".agenda-completed").filter({hasText: "Comprobante recibido tres días después"})).toBeVisible();
  await page.screenshot({path: info.outputPath("agenda-servicio-retroactivo.png"), fullPage: true});
});

test("propuesta conserva varios conductores y permite buscar sus unidades y servicios por nombre", async ({page}, info) => {
  await page.goto("/");
  await page.getByRole("button", {name: "Agregar unidad", exact: true}).click();
  await page.getByLabel("Número de serie (VIN)", {exact: true}).fill("1HGCM82633A004352");
  await page.getByLabel("Placas", {exact: true}).fill("NXR-482-B");
  for (const [name, value] of [["Marca", "Toyota"], ["Modelo", "Corolla"], ["Año modelo", "2024"], ["Versión", "LE"], ["Carrocería", "Sedán"], ["Motor", "1.8L"], ["Transmisión", "CVT"], ["Tracción", "FWD"]]) await page.getByLabel(name, {exact: true}).fill(value);
  await page.getByLabel("Odómetro actual (km)").fill("28000");
  await page.getByLabel("Fecha de puesta en servicio").fill("2024-02-01");
  await page.getByLabel("Conductores asignados (opcional)", {exact: true}).fill("Ana   María López\nJosé Pérez\n ana maría lópez");
  await expect(page.getByLabel("Factor de intervalo", {exact: true})).not.toBeVisible();
  await page.getByText("Configuración avanzada", {exact: true}).click();
  await expect(page.getByLabel("Factor de intervalo", {exact: true})).toHaveValue("1");
  await page.getByRole("button", {name: "Agregar a flotilla"}).click();
  const vehicleLink = page.locator(".plate-link").filter({hasText: "NXR-482-B"});
  await expect(vehicleLink).toBeVisible();
  await page.getByRole("searchbox", {name: "Buscar por placa", exact: true}).fill("NXR-482-B");
  await page.getByRole("searchbox", {name: "Buscar por nombre", exact: true}).fill("jose perez");
  await expect(vehicleLink).toBeVisible();
  await page.getByRole("searchbox", {name: "Buscar por nombre", exact: true}).fill("conductor inexistente");
  await expect(vehicleLink).toHaveCount(0);
  await page.getByRole("searchbox", {name: "Buscar por nombre", exact: true}).fill("ana maria");
  await vehicleLink.click();
  await page.getByRole("button", {name: "Editar conductores", exact: true}).click();
  await expect(page.getByLabel("Conductores asignados (opcional)", {exact: true})).toHaveValue("Ana María López\nJosé Pérez");
  await page.getByLabel("Conductores asignados (opcional)", {exact: true}).fill("Ana María López\nLucía García");
  await page.getByRole("button", {name: "Guardar conductores", exact: true}).click();
  await expect(page.getByText("Conductores actualizados.", {exact: true})).toBeVisible();
  await page.reload();
  await expect(page.locator(".vehicle-drivers-panel")).toContainText("Lucía García");
  await expect(page.locator(".vehicle-drivers-panel")).not.toContainText("José Pérez");
  await page.getByRole("link", {name: "Calendario", exact: true}).click();
  await page.getByRole("button", {name: "Registrar servicio realizado", exact: true}).click();
  await page.getByLabel("Unidad del servicio").selectOption({label: "NXR-482-B · Toyota Corolla"});
  await page.getByLabel("Fecha real del servicio").fill(isoDay(-4));
  await page.locator('input[name="manual_description"]').fill("Cambio de batería");
  await page.getByRole("button", {name: "Guardar servicio realizado"}).click();
  await expect(page.getByText("Guardado", {exact: true})).toBeVisible();
  await page.getByRole("searchbox", {name: "Buscar por placa", exact: true}).fill("NXR-482-B");
  await page.getByRole("searchbox", {name: "Buscar por nombre", exact: true}).fill("lucia garcia");
  await expect(page.locator(".agenda-completed")).toContainText("Cambio de batería");
  await page.getByRole("searchbox", {name: "Buscar por nombre", exact: true}).fill("jose perez");
  await expect(page.locator(".agenda-completed")).toHaveCount(0);
  await page.getByRole("searchbox", {name: "Buscar por nombre", exact: true}).fill("lucia garcia");
  await page.setViewportSize({width: 390, height: 844});
  await expect(page.locator("body")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({path: info.outputPath("agenda-mobile.png"), fullPage: true});
  await page.locator(".agenda-completed .plate-link").first().click();
  await page.getByRole("button", {name: "Editar conductores", exact: true}).click();
  await page.getByLabel("Conductores asignados (opcional)", {exact: true}).fill("");
  await page.getByRole("button", {name: "Guardar conductores", exact: true}).click();
  await expect(page.getByText("Conductores actualizados.", {exact: true})).toBeVisible();
  await page.reload();
  await expect(page.locator(".vehicle-drivers-panel").getByText("Sin conductor asignado", {exact: true})).toBeVisible();
});

test("abrir una propuesta anterior conserva sus cambios sin inventar conductores", async ({page, request}) => {
  const response = await request.get("/proposal/fleet.json");
  expect(response.ok()).toBeTruthy();
  const snapshot = await response.json();
  for (const vehicle of snapshot.vehicles) delete vehicle.drivers;
  for (const row of Object.values(snapshot.details) as {vehicle: {drivers?: string[]}}[]) delete row.vehicle.drivers;
  const vehicle = snapshot.details["1"].vehicle;
  vehicle.plate = "ABC-789-X";
  const previousRecord = {id: "saved-old-record", vehicle_id: vehicle.id, plate: vehicle.plate, planned_date: isoDay(-3), performed_on: isoDay(-3), service_ids: ["manual-saved"], service_names: ["Servicio previo conservado"], status: "completed", provisional: false, explanation: "Captura administrativa previa.", notes: "No debe perderse al actualizar."};
  await page.goto("/");
  await page.evaluate(saved => localStorage.setItem("yokohama-propuesta-administrativa-v1", JSON.stringify(saved)), {...snapshot, revision: 1, appointments: [], completed: [previousRecord]});
  await page.reload();
  await page.locator(".plate-link").filter({hasText: vehicle.plate}).click();
  await expect(page.locator(".vehicle-drivers-panel").getByText("Sin conductor asignado", {exact: true})).toBeVisible();
  await page.getByRole("link", {name: "Calendario", exact: true}).click();
  await page.getByLabel("Mes de visitas").fill(isoDay(-3).slice(0, 7));
  await page.getByRole("searchbox", {name: "Buscar por placa", exact: true}).fill(vehicle.plate);
  await expect(page.locator(".agenda-completed")).toContainText("Servicio previo conservado");
  await expect(page.locator(".agenda-completed")).toContainText("No debe perderse al actualizar.");
});
